name=input("your name is: ")
lastname=input("your lastname is: ")
age=input("your age is: ")
gmail=input("your gmail is: ")
num1=int(input("enter first number: "))
num2=int(input("enter second number :"))
num3=int(input("enter third number"))
print(num1 + num2)
print(num2 - num1)
print(num3 * num1)
print(num2 / num1)
price=("100")
amount=("50")
print(price)
print(amount)
(price * amount)
print(f"your name is {name}. your lastname is {lastname}. your age is {age}. your gmail is {gmail}.")
 